version: "3"
services: 
    node-app:
        build: .
        image: parag56/geeksman-backend
        container_name: nodejs
        restart: unless-stopped
    nginx:
        image: nginx:stable-alpine
        ports: 
            - "5000:80"
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        container_name: webserver
        restart: unless-stopped    
        depends_on:
            - node-app
    redis:
        image: redis
    certbot:
        image: certbot/certbot
#     mongo:
#         image: mongo
#         environment: 
#             - MONGO_INITDB_ROOT_USERNAME=Parag
#             - MONGO_INITDB_ROOT_PASSWORD=Hello
#         volumes: 
#             - mongo-db:/data/db
