version: "3"
services: 
    node-app:
        build: .
        image: parag56/geeksman-backend
        container_name: nodejs
        restart: unless-stopped
    nginx:
        image: nginx:stable-alpine
        ports: 
            - "5000:80"
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        container_name: webserver
        restart: unless-stopped    
        depends_on:
            - node-app
    redis:
        image: redis
    letsencrypt:
        image: quay.io/letsencrypt/letsencrypt:latest
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - /etc/letsencrypt:/etc/letsencrypt 
            - /var/lib/letsencrypt:/var/lib/letsencrypt 
        command: certonly -n -m paragthakur56@gmail.com -d geeksbackend.centralindia.cloudapp.azure.com --standalone --agree-tos    
#     mongo:
#         image: mongo
#         environment: 
#             - MONGO_INITDB_ROOT_USERNAME=Parag
#             - MONGO_INITDB_ROOT_PASSWORD=Hello
#         volumes: 
#             - mongo-db:/data/db
