version: "3"
services: 
    node-app:
        build: .
        image: parag56/geeksman-backend
        container_name: nodejs
        restart: unless-stopped
    nginx:
        image: nginx:stable-alpine
        ports: 
            - "5000:80"
        volumes: 
            - web-root:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        container_name: webserver
        restart: unless-stopped    
        depends_on:
            - node-app
    redis:
        image: redis
    certbot:
        image: certbot/certbot
        container_name: certbot
        depends_on:
            - nginx
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root:/var/www/html
        command: certonly --webroot --webroot-path=/var/www/html --email paragthakur56@gmail.com --agree-tos --no-eff-email --staging -d geeksbackend.centralindia.cloudapp.azure.com     

#     mongo:
#         image: mongo
#         environment: 
#             - MONGO_INITDB_ROOT_USERNAME=Parag
#             - MONGO_INITDB_ROOT_PASSWORD=Hello
#         volumes: 
#             - mongo-db:/data/db
volumes:
    certbot-etc:
    certbot-var:
    web-root:            