version: "3"
services: 
    nginx:
        ports:
            - "5000:80"
    node-app:
        build: 
            context: . 
            args:
                NODE_ENV: development 
        volumes: 
            - ./:/app
            - /app/node_modules
        env_file: 
            - ./config/dev.env    
        command:    npm run dev
        