version: "3"
services: 
    nginx:
        ports: 
            - "80:80"
            - "443:443"
    node-app:
        build: 
            context: . 
            args:
                NODE_ENV: production
        env_file: 
            - ../.env
        command:    node server.js
    