version: "3"
services: 
    nginx:
        ports:
            - "80:80"
        volumes: 
            - ./nginx/defaultdev.conf:/etc/nginx/conf.d/default.conf
    node-app:
        build: 
            context: . 
            args:
                NODE_ENV: development 
        volumes: 
            - ./:/app
            - /app/node_modules
        env_file: 
            - ./config/dev.env    
        command:    npm run dev
        